### ISSUE TITLE
problems using ssl

### ISSUE THREAD

**Issue by SilentCicero** [mattdesl/budo#171]
``` budo src/app.js:bundle.js -P --ssl --cors```

Having trouble running ssl with budo. Seems to be looking for a cert and key file, when it should generate it with `pem`. Thoughts?

```
> weifund-dapp-basic@0.1.0 start /home/nick/github/weifund-dapp-basic
> budo src/app.js:bundle.js -P --ssl --cors

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'cert.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at createServer (/home/nick/npm-global/lib/node_modules/budo/lib/server.js:8:14)
    at createBudo (/home/nick/npm-global/lib/node_modules/budo/lib/budo.js:116:16)
    at Function.budoCLI [as cli] (/home/nick/npm-global/lib/node_modules/budo/index.js:55:18)
    at Object.<anonymous> (/home/nick/npm-global/lib/node_modules/budo/bin/cmd.js:7:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by SilentCicero** [comment]
I made a PR to make some additions to the SSL/cors support:

https://github.com/mattdesl/budo/pull/172 -- re this article: https://williambert.online/2013/06/allow-cors-with-localhost-in-chrome/

**Comment by SilentCicero** [comment]
Just updated by `budo` package. It now works, however, the I get this cert error:

net::err_cert_authority_invalid

Thoughts?
