### ISSUE TITLE
budo fails in `npm run` scripts

### ISSUE THREAD

**Issue by eugeneware** [mattdesl/budo#191]
Given a package.json like:

``` json
{
  "scripts": {
    "start": "budo app.js:bundle.js --live",
  },
  "dependencies": {
    "browserify": "^13.1.1",
    "budo": "^9.2.2"
  }
}
```

If you try to run the script:

``` bash

$ npm start

> @ start /Users/eugeneware/Dropbox/work/scratch/gl-alias
> budo app.js:bundle.js --live

module.js:471
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/eugeneware/Dropbox/work/scratch/gl-alias/node_modules/.bin/budo:7:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/eugeneware/.nvm/versions/node/v6.9.1/bin/node" "/Users/eugeneware/.nvm/versions/node/v6.9.1/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ start: `budo app.js:bundle.js --live`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'budo app.js:bundle.js --live'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     budo app.js:bundle.js --live
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eugeneware/Dropbox/work/scratch/gl-alias/npm-debug.log
```

This because the cli `budo` lives in `node_modules/.bin` and the reference in [`cmd.js`](https://github.com/mattdesl/budo/blob/master/bin/cmd.js#L7) is a relative URL.

**Comment by mattdesl** [comment]
I've never seen this issue before and I've tested across a lot of machines / node versions. Perhaps the install is corrupted or your npm settings are very atypical. Can you try uninstalling/reinstalling:

```sh
npm uninstall budo
npm uninstall -g budo # any global copy...
npm install budo --save-dev
```

You can also try deleting (or backing up) your `node_modules` and re-installing your project.

**Comment by eugeneware** [comment]
@mattdesl I think you're right. It's a configuration issue. I think I had `nvm` running twice in my `.bash_profile` which was creating issues.

For whatever reason, the issue seems to be gone now.

Thanks so much for your reply though!

I'm closing this issue.
