### ISSUE TITLE
Crash when rebuilding linked dependency

### ISSUE THREAD

**Issue by chojje** [mattdesl/budo#248]
I have linked a dependency of my app using `npm link` in `my-dep` and running `npm link my-dep` in the app. Starting the app with `npm start` works fine, but when I run `npm run build` to rebuild the dependency while the server is running, it crashes with the following error messages

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, stat '<dep-path>\dist\cwm'
Emitted 'error' event at:
    at FSWatcher._handleError (<app-path>\node_modules\budo\node_modules\chokidar\index.js:260:10)
    at FSWatcher.<anonymous> (<app-path>\node_modules\budo\node_modules\chokidar\lib\nodefs-handler.js:470:14)
    at FSReqWrap.oncomplete (fs.js:153:21)
```

What might cause this issue?

**Comment by ccysmd** [comment]
Don't put your files under Administrator, put them at the desktop or D drive or other ordinary folders
