### ISSUE TITLE
Error: No element indexed by 0

### ISSUE THREAD

**Issue by scottcorgan** [mattdesl/budo#83]
Not sure where this error is coming from but here is my stack trace:

```
> budo spike/index.js --live -- -t [babelify --stage 0 ] | garnish

 info budo: Server running at http://10.0.64.254:9966/ (connect)
 info budo: LiveReload running on 35729
/Users/scottcorgan/www/laurelandwolf/data/node_modules/budo/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/source-map/lib/source-map/array-set.js:93
    throw new Error('No element indexed by ' + aIdx);
    ^

Error: No element indexed by 0
    at ArraySet_at [as at] (/Users/scottcorgan/www/laurelandwolf/data/node_modules/budo/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/source-map/lib/source-map/array-set.js:93:11)
    at SourceMapConsumer.<anonymous> (/Users/scottcorgan/www/laurelandwolf/data/node_modules/budo/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/source-map/lib/source-map/source-map-consumer.js:147:69)
    at Array.map (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/scottcorgan/www/laurelandwolf/data/node_modules/budo/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/source-map/lib/source-map/source-map-consumer.js:146:16)
    at module.exports (/Users/scottcorgan/www/laurelandwolf/data/node_modules/budo/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/lib/mappings-from-map.js:13:12)
    at Combiner._addExistingMap (/Users/scottcorgan/www/laurelandwolf/data/node_modules/budo/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/index.js:70:18)
    at Combiner.addFile (/Users/scottcorgan/www/laurelandwolf/data/node_modules/budo/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/index.js:113:12)
    at DestroyableTransform.write [as _transform] (/Users/scottcorgan/www/laurelandwolf/data/node_modules/budo/node_modules/browserify/node_modules/browser-pack/index.js:63:23)
    at DestroyableTransform.Transform._read (/Users/scottcorgan/www/laurelandwolf/data/node_modules/budo/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/scottcorgan/www/laurelandwolf/data/node_modules/budo/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
```

**Comment by mattdesl** [comment]
Thanks, looks related to https://github.com/Jam3/hihat/issues/23.

Is there any way I can reproduce? Can you also try doing `budo --version` and let me know the result?

**Comment by scottcorgan** [comment]
You can clone a repo and run:

```
git clone git@github.com:laurelandwolf/data.git
cd data
npm install
npm run spike
```

`budo --version` output:

```
λ: node_modules/.bin/budo --version
budo v5.1.1
browserify v11.2.0
watchify v3.4.0
```

**Comment by mattdesl** [comment]
Hmm, `budo spike/index.js` isn't working since there is no `spike/index.js` file or `spike` folder.

**Comment by scottcorgan** [comment]
Oh ya, it's only local. Does that error happen if you create that file?

**Comment by mattdesl** [comment]
I created `spike/index.js` with the following:

```js
import foo from '../src'
```

Then the `npm run spike` command runs with no problems. `npm test` also works with no errors or test failures FWIW.

Does the following produce the same error for you?

```sh
npm install watchify
watchify spike/index.js -v -t [babelify --stage 0 ] -o test-bundle.js
```

**Comment by scottcorgan** [comment]
Now it's working. That's weird. I'll close for now and reopen if I can reproduce.

Thanks!
